# Deployment 配置
apiVersion: apps/v1 # 自定义
kind: Deployment
metadata: #用元数据对Deployment做描述
  name: caculator
  namespace: default # 默认就是default，可以不写
spec:
  # rs 资源对象定义区
  replicas: 3 # rs控制副本数量，指定副本数量为3
  selector: # 定义选择器
    matchLabels: #匹配的标签，下面定义了3个标签，将会选择有这些标签的pod
      app: caculator
  # pod 资源对象定义区
  template:
    metadata:
      labels: #定义标签，要和上面selector的matchLabels保持一直，否则关联不起来
        app: caculator
    spec:
      containers: # 定义pod中的容器，一个pod可以运行多个容器
      - name: caculator
        image: yamon955/caculator:v1.0
        ports:
        - containerPort: 9000 #指定容器运行的端口
        resources:
          limits:         # 容器可以使用的最大资源量
            cpu: 500m
            memory: 256Mi
          requests:       # 容器启动时所需的最小资源量
            cpu: 250m
            memory: 128Mi
---
# Service 配置
apiVersion: v1 #所有资源文件一开始都要设置apiVersion
kind: Service
metadata:
  name: caculator
spec:
  type: NodePort
  selector:
    app: caculator
  ports:
  - protocol: TCP
    port: 9000        #集群内部访问的目标端口
    targetPort: 9000  #pod上的端口，从port/nodePort上来的数据，经过kube-proxy流入到后端pod的targetPort上，最后进入容器，与制作容器时暴露的端口一致
    nodePort: 30001   #集群外部访问的目标端口 （通常在 30000-32767 之间）