// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: caculator.proto

package caculator

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operators int32

const (
	Operators_ADD Operators = 0
	Operators_SUB Operators = 1
	Operators_MUL Operators = 2
	Operators_DIV Operators = 3
)

// Enum value maps for Operators.
var (
	Operators_name = map[int32]string{
		0: "ADD",
		1: "SUB",
		2: "MUL",
		3: "DIV",
	}
	Operators_value = map[string]int32{
		"ADD": 0,
		"SUB": 1,
		"MUL": 2,
		"DIV": 3,
	}
)

func (x Operators) Enum() *Operators {
	p := new(Operators)
	*p = x
	return p
}

func (x Operators) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operators) Descriptor() protoreflect.EnumDescriptor {
	return file_caculator_proto_enumTypes[0].Descriptor()
}

func (Operators) Type() protoreflect.EnumType {
	return &file_caculator_proto_enumTypes[0]
}

func (x Operators) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Operators) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Operators(num)
	return nil
}

// Deprecated: Use Operators.Descriptor instead.
func (Operators) EnumDescriptor() ([]byte, []int) {
	return file_caculator_proto_rawDescGZIP(), []int{0}
}

type CaculateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A  *float64   `protobuf:"fixed64,1,req,name=a" json:"a,omitempty"`
	B  *float64   `protobuf:"fixed64,2,req,name=b" json:"b,omitempty"`
	Op *Operators `protobuf:"varint,3,req,name=op,enum=trpc.test.caculator.Operators" json:"op,omitempty"`
}

func (x *CaculateReq) Reset() {
	*x = CaculateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaculateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaculateReq) ProtoMessage() {}

func (x *CaculateReq) ProtoReflect() protoreflect.Message {
	mi := &file_caculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaculateReq.ProtoReflect.Descriptor instead.
func (*CaculateReq) Descriptor() ([]byte, []int) {
	return file_caculator_proto_rawDescGZIP(), []int{0}
}

func (x *CaculateReq) GetA() float64 {
	if x != nil && x.A != nil {
		return *x.A
	}
	return 0
}

func (x *CaculateReq) GetB() float64 {
	if x != nil && x.B != nil {
		return *x.B
	}
	return 0
}

func (x *CaculateReq) GetOp() Operators {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return Operators_ADD
}

type CaculateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ans *float64 `protobuf:"fixed64,1,opt,name=ans" json:"ans,omitempty"`
}

func (x *CaculateRsp) Reset() {
	*x = CaculateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_caculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaculateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaculateRsp) ProtoMessage() {}

func (x *CaculateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_caculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaculateRsp.ProtoReflect.Descriptor instead.
func (*CaculateRsp) Descriptor() ([]byte, []int) {
	return file_caculator_proto_rawDescGZIP(), []int{1}
}

func (x *CaculateRsp) GetAns() float64 {
	if x != nil && x.Ans != nil {
		return *x.Ans
	}
	return 0
}

var File_caculator_proto protoreflect.FileDescriptor

var file_caculator_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x63, 0x61, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x59, 0x0a, 0x0b, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x01,
	0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x02, 0x28, 0x01, 0x52, 0x01,
	0x62, 0x12, 0x2e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x1e, 0x2e,
	0x74, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x63, 0x61, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x02, 0x6f,
	0x70, 0x22, 0x1f, 0x0a, 0x0b, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61,
	0x6e, 0x73, 0x2a, 0x2f, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12,
	0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x42, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x55, 0x4c, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49,
	0x56, 0x10, 0x03, 0x32, 0x5b, 0x0a, 0x09, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x4e, 0x0a, 0x08, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x74,
	0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x63, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x20,
	0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x63, 0x61, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x59,
	0x61, 0x6d, 0x6f, 0x6e, 0x39, 0x35, 0x35, 0x2f, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x61, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
}

var (
	file_caculator_proto_rawDescOnce sync.Once
	file_caculator_proto_rawDescData = file_caculator_proto_rawDesc
)

func file_caculator_proto_rawDescGZIP() []byte {
	file_caculator_proto_rawDescOnce.Do(func() {
		file_caculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_caculator_proto_rawDescData)
	})
	return file_caculator_proto_rawDescData
}

var file_caculator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_caculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_caculator_proto_goTypes = []interface{}{
	(Operators)(0),      // 0: trpc.test.caculator.Operators
	(*CaculateReq)(nil), // 1: trpc.test.caculator.CaculateReq
	(*CaculateRsp)(nil), // 2: trpc.test.caculator.CaculateRsp
}
var file_caculator_proto_depIdxs = []int32{
	0, // 0: trpc.test.caculator.CaculateReq.op:type_name -> trpc.test.caculator.Operators
	1, // 1: trpc.test.caculator.Caculator.Caculate:input_type -> trpc.test.caculator.CaculateReq
	2, // 2: trpc.test.caculator.Caculator.Caculate:output_type -> trpc.test.caculator.CaculateRsp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_caculator_proto_init() }
func file_caculator_proto_init() {
	if File_caculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_caculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaculateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_caculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaculateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_caculator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_caculator_proto_goTypes,
		DependencyIndexes: file_caculator_proto_depIdxs,
		EnumInfos:         file_caculator_proto_enumTypes,
		MessageInfos:      file_caculator_proto_msgTypes,
	}.Build()
	File_caculator_proto = out.File
	file_caculator_proto_rawDesc = nil
	file_caculator_proto_goTypes = nil
	file_caculator_proto_depIdxs = nil
}
